# Generated by Django 3.2.5 on 2023-01-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('auteur', models.CharField(max_length=50)),
                ('Key', models.CharField(max_length=12)),
                ('paroles', models.TextField(max_length=50)),
                ('Partie_eucharistique', models.CharField(max_length=50)),
                ('temps_liturgique', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choriste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=12)),
                ('voice', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partie_eucharistique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Temps_liturgique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_present', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.choriste')),
            ],
        ),
    ]
