# Generated by Django 3.2.5 on 2023-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230113_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chant',
            name='temps_liturgique',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
