# Generated by Django 3.2.5 on 2023-01-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chant_temps_liturgique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chant',
            old_name='Key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='chant',
            old_name='Partie_eucharistique',
            new_name='partie_eucharistique',
        ),
    ]
